### ISSUE TITLE
Criar um Framework para portar a IA.

### ISSUE THREAD

**Issue by gabrielsimas** [paulosobreira/f1mane#1]
Fala Paulo.

Gostei demais desse seu projeto. Tem como a gente criar um engine no estilo API? Eu estava com um projeto de simulador tipo elifoot, que é de futebol, com F1, onde a gente não veria a corrida, mas veria as posições e traçava as estratégias. E o seu Jogo é perfeito. Gostei da IA dele.

**Comment by paulosobreira** [comment]
Oi Luís, tudo bom?
 
Ultimamente venho trabalhando na versão online do jogo http://games-sowbreira.rhcloud.com/f1mane/.
 
Me fala do seu projeto, eu comecei o f1mane como um simulador somente com informações da corrida. Depois que foi ganhando mais cara de jogo.
 
Que tipo de API vc tem em mente?
 
Att . Paulo Sobreira

**Comment by gabrielsimas** [comment]
Oi Paulo.

Pois é, o seu jogo é um manager com gráficos, eu já estava pensando em um manager sem gráficos mesmo. No que tange a API, eu estava pensando em algo como Serviço mesmo e no front end, utilizar um AngularJS por ser bem mais dinâmico para jogos. A sua idéia foi muito legal, eu pensei em fazer algo assim, mas me perdi nas regras de negócio, fiquei meio travado nas regras para física e afins e como emular a pista...

Você vai abrir o código da versão online?

**Comment by paulosobreira** [comment]
A versão online está aqui já. Tem um build do ant  e tudo roda em Servlet e Applet transformado Web Start que roda com qualquer banco de dados relacional. É uma tecnologia bem antiga mas me da controle total do que esta acontecendo. JS é bom mas para mim ainda abstrai demais coisas como sockets e threads. Talvez o mais forte no meu conhecimento atual seja a API 2D do HTML5. Estou esperando a tecnologia evoluir para brincar em desenvolver um jogo bem a baixo nível para fomentar o conhecimento na tecnologia. Se que fazer um jogo comercial recomendo fortemente o uso de um framework de mercado.

**Comment by gabrielsimas** [comment]
Paulo.

Obrigado pela sua resposta e apoio. Mas, não pretendo fazer nada comercial não. Gostei muito do seu engine. Caso eu faça alguma melhoria ou correção, mando um pull pra você.

Forte Abraço
